### ISSUE TITLE
All weather info doesn't update

### ISSUE THREAD

**Issue by Steph1116** [jake1164/Pico-RGB-Matrix-Weather-Clock#42]
The numerical temperature, feels like, humidity and wind will only be correct if the unit is powered of and then back on. The current conditions seem to be correct but difficult to tell as it can be clear skies the whole day for example.

**Comment by jake1164** [comment]
Just getting back from vacation, I'll take a look next weekend and see if I can see anything or some way to indicate its been updated.

________________________________
From: Steph1116 ***@***.***>
Sent: Thursday, April 13, 2023 9:09 PM
To: jake1164/Pico-RGB-Matrix-Weather-Clock ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jake1164/Pico-RGB-Matrix-Weather-Clock] All weather info doesn't update (Issue #42)


The numerical temperature, feels like, humidity and wind will only be correct if the unit is powered of and then back on. The current conditions seem to be correct but difficult to tell as it can be clear skies the whole day for example.

**Comment by Steph1116** [comment]
No problem. No rush.

**Comment by jake1164** [comment]
This is partially resolved.. I need to time out the weather and icon if the weather api has stopped pulling data though.

**Comment by jake1164** [comment]
This should be resolved now that I check and if the API call fails more than 5 times (roughly a min) it will turn off the temperature and the weather icon until a new API call is received. #49 #47
