### ISSUE TITLE
Fresh install, can't get anything working.

### ISSUE THREAD

**Issue by Steph1116** [jake1164/Pico-RGB-Matrix-Weather-Clock#71]
I reinstalled all code from the zip file, edited the settings.toml with my api and wifi and I'm getting an openweather error. I created a new api and still won't load pas the sun icon and dev text. I'd like to get this working but ran out of time today to fiddle with it. 

Also, do you think maybe we can get a code without weather, just date and time. May be an option to revert to until the weather can get sorted out. Thanks

**Comment by jake1164** [comment]
Hmm.. I originally had a setting in the toml file to enable / disable.. guess I removed it.  I'll add that to the list of items to add to it.

If you run the code.py file from thonny it should give more information about the error, that would help me.

Also it will list the url's being accessed and you can click on those to see if its code issue or account issue.


________________________________
From: Steph1116 ***@***.***>
Sent: Friday, November 24, 2023 10:24 AM
To: jake1164/Pico-RGB-Matrix-Weather-Clock ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jake1164/Pico-RGB-Matrix-Weather-Clock] Fresh install, can't get anything working. (Issue #71)


I reinstalled all code from the zip file, edited the settings.toml with my api and wifi and I'm getting an openweather error. I created a new api and still won't load pas the sun icon and dev text. I'd like to get this working but ran out of time today to fiddle with it.

Also, do you think maybe we can get a code without weather, just date and time. May be an option to revert to until the weather can get sorted out. Thanks

**Comment by jake1164** [comment]
You can always revert to an older version.. under [releases](https://github.com/jake1164/Pico-RGB-Matrix-Weather-Clock/releases) scroll down to the last known version for you.

**Comment by Steph1116** [comment]
I don't remember what version I had before. I'll play around more once I get back home. And I'll also post the error here.

**Comment by jake1164** [comment]
Also let me know what version of CircuitPython you are running.. that could be a factor.

**Comment by Steph1116** [comment]
After much fighting, nuking, reinstating, updating, lol, I have it working. I think it was a combination of the firmware and something I messed up with the weather api. Something to possibly fix though would be the settings.toml file. It's listed as settings.toml.default. I had to remove default to get it to work. Thanks for your help. I wouldn't have thought to update the firmware.

**Comment by jake1164** [comment]
Yes its a .default so that it wont overwrite an existing settings.toml file on accident.
________________________________
